"""Initial_migration

Revision ID: 93af19e2b883
Revises: 
Create Date: 2026-05-03 14:25:38.022433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93af19e2b883'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_fr', sa.String(length=80), nullable=False),
    sa.Column('name_ar', sa.String(length=80), nullable=True),
    sa.Column('icon_slug', sa.String(length=50), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_essential', sa.Boolean(), nullable=False),
    sa.Column('is_income', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('wilaya_code', sa.Integer(), nullable=False),
    sa.Column('salary_day', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rib', sa.String(length=20), nullable=False),
    sa.Column('account_type', sa.Enum('CCP', 'EPARGNE', 'CPA', 'BUSINESS', name='accounttype'), nullable=False),
    sa.Column('balance_da', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rib')
    )
    op.create_table('budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('limit_da', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('period_type', sa.Enum('MENSUEL', 'HEBDOMADAIRE', 'RAMADAN', name='periodtype'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('insight_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARN', 'CRITICAL', 'GOOD', 'CONTEXT', name='insightseverity'), nullable=False),
    sa.Column('message_fr', sa.Text(), nullable=False),
    sa.Column('message_ar', sa.Text(), nullable=True),
    sa.Column('rule_id', sa.String(length=10), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('predicted_for_month', sa.String(length=7), nullable=False),
    sa.Column('predicted_expense_da', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('predicted_balance_da', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('confidence_interval_da', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('amount_da', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('type', sa.Enum('CREDIT', 'DEBIT', name='transactiontype'), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('channel', sa.Enum('ATM', 'ONLINE', 'VIREMENT', 'MANDAT', 'CIB', 'BARIDIMOB', 'CASH', name='transactionchannel'), nullable=False),
    sa.Column('status', sa.Enum('COMPLETED', 'PENDING', 'REJECTED', name='transactionstatus'), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('predictions')
    op.drop_table('insights')
    op.drop_table('budgets')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('categories')
    # ### end Alembic commands ###
